name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t api .

      - name: Run tests
        run: echo "Running tests..."
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Pulling latest changes..."
            cd /home/${{ secrets.VPS_USER }}/api
            git pull origin main
                                    
            echo "Stopping old container..."
            docker stop api || true
            docker rm api || true

            echo "Building and running new container..."
            docker build -t api .
            docker run -d -p 8000:8000 --name api api
